### ISSUE TITLE
Como conseguiu os dados?

### ISSUE THREAD

**Issue by ikaromn** [ronaldoaf/Repositorio_Cartola#1]
Iae cara, beleza.

Percebi que você tem json com informações dos jogadores a cada rodada.

Como você conseguiu obter esses dados?

To pensando em criar um repositório para analise desses dados e tentar prever se o cara vai conseguir ir bem ou mal na rodada seguinte.

**Comment by ronaldoaf** [comment]
Opa 

eu peguei do site da globo mesmo no endereço
https://api.cartolafc.globo.com/atletas/mercado
programei um código para pegar e salvar num disco em meu servidor.

tenho as 7 primeiras rodadas de 2016 aqui http://aposte.me/cartola/data.json

e tenho todas as rodadas de 2015 em um outro formato

**Comment by ronaldoaf** [comment]
Aqui eu tenho os dados de 2015
https://github.com/ronaldoaf/analise-cartola-2015

arquivo jogadores.json
